service: real-estate-crawler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 28
  memorySize: 2048
  versionFunctions: false
  deploymentBucket:
    name: real-estate-crawler-dev

functions:
  urlCrawler:
    handler: handler.urlCrawler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-layers

custom:
  serverless-layers:
    # applies for all lambdas 
    - common:
        dependenciesPath: ./package.json
